### ISSUE TITLE
谢谢大佬解决了我的难题

### ISSUE THREAD

**Issue by cyberspacelee** [mlzxgzy/XXY_Search#1]
3月份的时候我也抓包搞了个python程序，前段时间程序好像更新了，再次用直接把我号给封禁了，再次换号抓包，发现有个token，不知道是啥加密成的，就放弃了

**Comment by mlzxgzy** [comment]
我号也被封了一个😂
就很难受
我看看能不能尽量跟进跟进

**Comment by cyberspacelee** [comment]
去找他们的QQ客服，说自己号没办法用了，装傻让他们解封，我就是这样搞的
不过现在毛概考完了，用不到了
期待大佬接着更新

**Comment by mlzxgzy** [comment]
哦吼 学到了学到了
我这就去对线
